/**
 * What each control does, in a sentence or two, for the status bar.
 *
 * Keyed the way the controls are tagged for the search (`data-search-key`):
 * a setting by its key, a tab as `tab:<id>`, a section of Styles as
 * `subtab:<id>`, a style property as `property:<name>`. The English half of
 * the catalogue, like the labels; a locale supplies its own.
 *
 * Written for the person hovering, not the file: what changes on the page,
 * and what to reach for instead when this is not the control they want.
 */
export const EN_HELP: Readonly<Record<string, string>> = {
  // ---------------------------------------------------------------- tabs
  "tab:scripture":
    "Which books go into the PDF, and in what order. Tick a book to include it; drag to reorder.",
  "tab:template":
    "Eight kinds of book to start from. Choosing one writes its settings into your project, where you can then change them one at a time.",
  "tab:contents":
    "What appears on the page — front matter, chapter and verse numbers — and where books, chapters and verses start.",
  "tab:paragraph": "How a paragraph is set: justification, poetry indents, drop caps and quotations.",
  "tab:notes": "Footnotes and cross-references: whether they appear, their marks, and where the references go.",
  "tab:headers":
    "The running head and the page number on each side of the spread: six slots a side, each a template of fields.",
  "tab:page": "The trim size, the columns and the margins, drawn to scale.",
  "tab:styles": "How each kind of element looks: the body font, headings, poetry, numbers, notes, character styles.",
  "tab:figures": "What the build does about a figure whose file is not there.",
  "tab:metadata": "What the PDF says about itself: publisher, subject, its file name, how far its bookmarks reach.",
  "subtab:typography": "The body font, its size and leading, and whether words are hyphenated.",
  "subtab:headings": "Section headings, parallel-passage lines, psalm superscriptions and speaker lines.",
  "subtab:paragraphs": "Body paragraphs, centred paragraphs and introductions: their spacing, indent and alignment.",
  "subtab:poetry": "Poetry lines by level: their indents and the space around them.",
  "subtab:numbers": "The chapter number and the verse number: face, size, and where the chapter number sits.",
  "subtab:notes": "Footnotes and cross-references at the foot of the page.",
  "subtab:characters": "Bold, italic, emphasis, added words, the divine name, the words of Jesus, quoted text.",
  "subtab:furniture": "The running head, the page number and figure captions.",
  "subtab:inspect": "Every property of every element, and where each value came from — the built-in set, this project, or inheritance.",

  // ------------------------------------------------------------ settings
  "project.name": "The publication's name: the PDF's title, and its file name unless one is set.",
  "project.language": "The language of the Scripture, as a BCP-47 tag such as ta or en. Sets hyphenation and the PDF's language.",
  "project.author": "The publisher, written into the PDF's properties. Empty leaves it out.",
  "project.subject": "The PDF's subject property. Empty leaves it out.",
  "books.order": "The books in the order they are bound. Set on the Scripture tab by dragging.",
  "books.include": "Which books go into the PDF. Set on the Scripture tab by ticking.",
  "page.size": "The trim size of the page: a name such as a5 or trade, or two lengths such as 6x9in.",
  "page.columns": "One column or two. Most Bibles are two; a reader's edition is one.",
  "page.margin_top": "From the top edge of the page to the text.",
  "page.margin_bottom": "From the foot of the text to the bottom edge, with room for the page number.",
  "page.margin_inner": "The margin at the spine — on the left of a right-hand page, the right of a left-hand one.",
  "page.margin_outer": "The margin at the outer edge, where a thumb goes.",
  "page.column_gap": "The space between the two columns.",
  "page.header_gap": "From the running head down to the text.",
  "page.footer_gap": "From the text down to the page number.",
  "typography.font_family": "The body face. A font in the project's assets/fonts folder is used by file; any other by name, from the fonts installed on this machine.",
  "typography.font_size": "The body size. Everything else that is not set in a style scales from this.",
  "typography.leading": "The distance from one baseline to the next — a length, not a multiple.",
  "typography.hyphenation": "Whether words may break at a line's end, with a hyphen, in the project's language.",
  "typography.justify": "Whether lines are set to the full measure, or ragged at the right.",
  "typography.keep_poetry_indentation": "Whether poetry keeps the indents its levels ask for, or is set flush like prose.",
  "numbering.show_chapter_numbers": "Whether chapter numbers appear, and where: in the text, or in the left or right margin of the column.",
  "numbering.chapter_number_placement": "Where the chapter number sits: in the text, or in a margin beside the line the chapter begins on.",
  "numbering.show_verse_numbers": "Whether verse numbers appear, and where: in the text before each verse, or in a margin beside its line.",
  "numbering.verse_number_placement": "Where the verse numbers sit: in the text, or in a margin beside the line each verse begins on.",
  "numbering.hide_first_verse_number": "Leave verse 1 unnumbered where the chapter number already marks the place. Set for you when drop caps are on.",
  "numbering.show_chapter_labels": "Print the words a translation gives a chapter — USFM's \\cl, such as அத்தியாயம் 1 — where it has them.",
  "numbering.margin_gap": "The space between a number set in the margin and the edge of the column.",
  "contents.show_book_introductions": "Print each book's introduction, where the translation has one.",
  "contents.show_introductory_outlines": "Print each book's outline, where the translation has one.",
  "contents.show_section_headings": "Print the section headings the translation carries.",
  "contents.drop_caps": "Open each chapter with a drop cap: a letter or a number set large, the first lines running round it. The first verse then goes unnumbered.",
  "contents.drop_cap_of": "What drops: the chapter's first letter — its first syllable in a script that writes one as several characters — with the number on a line above it; or the chapter number itself.",
  "contents.drop_cap_lines": "How many lines the drop cap spans. Three is the convention.",
  "contents.book_starts": "Where each book after the first begins: on the run, the next column, the next page, a chosen side, or after a blank page.",
  "contents.chapter_starts": "Where each chapter after a book's first begins: on the run, the next column, the next page, or a chosen side.",
  "contents.verse_starts": "Whether each verse follows on in the paragraph, or begins a line of its own.",
  "contents.start_verses": "A book or chapter with fewer than this many of its opening verses fitting in the column moves to the next column, whatever its start says. 0 turns this off.",
  "quotes.start": "Whether a quotation begins where the text reaches it, or on a line of its own with the line before ended.",
  "quotes.line_indent": "How far in a quotation on its own line begins — twice this for a quotation inside one.",
  "quotes.hang": "What the lines after a quotation begins line up with: nothing, the opening mark, or the word after it. Set in the PDF, not shown on the page here.",
  "quotes.indent_gap": "Added to that alignment once per level, so a quotation inside one stands further in.",
  "notes.show_footnotes": "Whether footnotes appear at the foot of the page, and what marks them: figures, letters, symbols, or no mark.",
  "notes.footnote_callers": "What marks a footnote in the text and at the foot: figures, letters, symbols, or nothing.",
  "notes.show_cross_references": "Whether cross-references appear, and what marks them.",
  "notes.cross_reference_callers": "What marks a cross-reference: figures, letters, symbols, or nothing.",
  "notes.cross_reference_placement": "Where cross-references go: the note area at the foot, in the text, or under the paragraph.",
  "notes.restart_numbering": "Where the marks start again from 1 or a: every chapter, every book, or never.",
  "assets.missing_figure": "A figure whose file is not there: stop the build and say so, or leave it out with a warning.",
  "output.name": "What the PDF file is called, inside the project's output folder. Empty names it after the publication.",
  "output.anchors": "How far the PDF's bookmarks and destinations reach: every chapter, every verse, or none.",
  "output.keep_intermediates": "Keep the typesetter's working files after a build, for looking into a problem.",
  strict: "Treat a warning in the settings as an error, so a build with a doubtful setting stops rather than guesses.",
  "headers.left_page.header_left": "The left slot of the running head on left-hand pages: text with fields in braces, such as {Book}.",
  "headers.left_page.header_center": "The centre slot of the running head on left-hand pages.",
  "headers.left_page.header_right": "The right slot of the running head on left-hand pages.",
  "headers.left_page.footer_left": "The left slot of the foot on left-hand pages.",
  "headers.left_page.footer_center": "The centre slot of the foot on left-hand pages, where the page number usually goes.",
  "headers.left_page.footer_right": "The right slot of the foot on left-hand pages.",
  "headers.right_page.header_left": "The left slot of the running head on right-hand pages.",
  "headers.right_page.header_center": "The centre slot of the running head on right-hand pages.",
  "headers.right_page.header_right": "The right slot of the running head on right-hand pages: text with fields in braces, such as {Range}.",
  "headers.right_page.footer_left": "The left slot of the foot on right-hand pages.",
  "headers.right_page.footer_center": "The centre slot of the foot on right-hand pages, where the page number usually goes.",
  "headers.right_page.footer_right": "The right slot of the foot on right-hand pages.",

  // ----------------------------------------------------- style properties
  "property:font_family": "The face this element is set in, when it is not the body font.",
  "property:font_size": "The size this element is set at.",
  "property:weight": "The weight: 400 is regular, 700 bold, on the OpenType scale.",
  "property:italic": "Set in the italic face, where the font has one.",
  "property:smallcaps": "Set in small capitals.",
  "property:space_above": "Space before the element.",
  "property:space_below": "Space after it.",
  "property:indent": "How far the whole block stands in from the margin.",
  "property:raise": "How far the element is lifted from the baseline — a verse number as a superior figure.",
  "property:align": "Start, centre, end, or justified.",
  "property:color": "The ink, as a hex colour such as #c81414.",
  "property:border": "A rule round the element.",
  "property:border_width": "How thick that rule is.",
  "property:own_line": "The element takes a line of its own, with the space above and below around it and the alignment deciding where on the line.",
  "property:gap_before": "Space before the element when it sits in the text.",
  "property:gap_after": "Space after it.",
};
