//! Typed errors and warnings shared by every BibleCompose stage.
//!
//! One `Diagnostic` type, produced by eight stages, rendered by one panel.
//! See ARCHITECTURE §10.
//!
//! Two rules are enforced here rather than by convention:
//!
//! * **A code cannot disagree with its stage.** Codes are generated from the
//!   stage that declares them ([`codes!`]), so `Stage::Config` cannot carry a
//!   `USFM-` code. DIA-001.
//! * **Diagnostics quote at most one elided source line.** NFR-010 asks logs
//!   not to record Scripture unnecessarily, which is easy at the start and
//!   impossible once a log format is relied upon. [`Quote::elided`] is the
//!   only way to attach source text.

use std::fmt;

use camino::Utf8PathBuf;
use serde::{Deserialize, Serialize};

/// Where a diagnostic came from. The prefix is the first half of every code
/// that stage can produce, which is what makes DIA-004's filtering a field
/// comparison rather than a string match.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Stage {
    Discovery,
    Usfm,
    Config,
    Style,
    Asset,
    Font,
    Backend,
    Output,
}

impl Stage {
    pub const fn prefix(self) -> &'static str {
        match self {
            Stage::Discovery => "PRJ",
            Stage::Usfm => "USFM",
            Stage::Config => "CFG",
            Stage::Style => "STY",
            Stage::Asset => "ASSET",
            Stage::Font => "FONT",
            Stage::Backend => "SILE",
            Stage::Output => "OUT",
        }
    }

    pub const fn all() -> &'static [Stage] {
        use Stage::*;
        &[Discovery, Usfm, Config, Style, Asset, Font, Backend, Output]
    }
}

impl fmt::Display for Stage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.prefix())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Severity {
    /// Blocks the build. Validation runs to completion first, so a blocked
    /// build reports every one of these at once (DIA-002).
    Error,
    /// The build proceeds (DIA-003).
    Warning,
    Info,
}

impl Severity {
    pub const fn blocks(self) -> bool {
        matches!(self, Severity::Error)
    }
}

impl fmt::Display for Severity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Severity::Error => "error",
            Severity::Warning => "warning",
            Severity::Info => "info",
        })
    }
}

/// A stable machine-readable code (DIA-001).
///
/// There is no public constructor taking an arbitrary string: every value is
/// generated by [`codes!`] from the stage that owns it, so the `id` and the
/// `stage` cannot drift apart.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Code {
    stage: Stage,
    id: &'static str,
}

/// Serialized as the bare code string — `"CFG-002"`, not a struct. The stage
/// is recoverable from the prefix, so writing both would be a way for the two
/// to disagree on the wire.
impl Serialize for Code {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.id)
    }
}

/// Deserialization is a lookup, not a construction: an unknown code is an
/// error rather than a `Code` nothing can interpret.
impl<'de> Deserialize<'de> for Code {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Code, D::Error> {
        let s = String::deserialize(d)?;
        code::ALL
            .iter()
            .find(|c| c.id == s)
            .copied()
            .ok_or_else(|| serde::de::Error::custom(format!("unknown diagnostic code {s:?}")))
    }
}

impl Code {
    pub const fn stage(self) -> Stage {
        self.stage
    }

    pub const fn as_str(self) -> &'static str {
        self.id
    }
}

impl fmt::Display for Code {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.id)
    }
}

/// Compile-time string equality, so [`codes!`] can assert that a group's
/// prefix literal really is the one its stage declares.
#[doc(hidden)]
pub const fn __str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// Declares codes grouped by the stage that owns them.
///
/// The prefix literal appears once per group and is **checked against
/// [`Stage::prefix`] at compile time**, so `Config "USFM" { … }` does not
/// build. `concat!` needs a literal, which is why the prefix is written rather
/// than derived — the const assertion is what closes the gap.
#[macro_export]
macro_rules! codes {
    ($( $stage:ident $prefix:literal { $( $name:ident = $id:literal ),* $(,)? } )*) => {
        $(
            const _: () = assert!(
                $crate::__str_eq($crate::Stage::$stage.prefix(), $prefix),
                concat!("diagnostic group ", stringify!($stage), " declares the wrong prefix"),
            );

            $(
                pub const $name: $crate::Code = $crate::Code::__declare(
                    $crate::Stage::$stage,
                    ::std::concat!($prefix, "-", $id),
                );
            )*
        )*

        /// Every code declared in this module, for the invariant test and for
        /// documentation generation.
        pub const ALL: &[$crate::Code] = &[ $( $( $name ),* ),* ];
    };
}

impl Code {
    /// Not for direct use — [`codes!`] is the supported constructor. Public
    /// only because the macro expands in the caller's crate.
    #[doc(hidden)]
    pub const fn __declare(stage: Stage, id: &'static str) -> Code {
        Code { stage, id }
    }
}

/// A position in a project file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceLoc {
    pub path: Utf8PathBuf,
    pub line: Option<u32>,
    pub column: Option<u32>,
}

impl SourceLoc {
    pub fn file(path: impl Into<Utf8PathBuf>) -> Self {
        SourceLoc {
            path: path.into(),
            line: None,
            column: None,
        }
    }

    pub fn at(path: impl Into<Utf8PathBuf>, line: u32, column: u32) -> Self {
        SourceLoc {
            path: path.into(),
            line: Some(line),
            column: Some(column),
        }
    }
}

impl fmt::Display for SourceLoc {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.path)?;
        if let Some(line) = self.line {
            write!(f, ":{line}")?;
            if let Some(column) = self.column {
                write!(f, ":{column}")?;
            }
        }
        Ok(())
    }
}

/// A Scripture reference, for diagnostics that can name one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScriptureRef {
    pub book: String,
    pub chapter: u16,
    pub verse: Option<u16>,
}

impl fmt::Display for ScriptureRef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} {}", self.book, self.chapter)?;
        if let Some(v) = self.verse {
            write!(f, ":{v}")?;
        }
        Ok(())
    }
}

/// At most one line of source text, elided to a bounded width.
///
/// NFR-010: logs should carry only the context needed to identify a problem.
/// Constructing this any other way is not possible, so a full verse cannot
/// reach the log by accident.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Quote(String);

impl Quote {
    pub const MAX: usize = 60;

    /// Takes one line, trims it, and elides the middle if it is too long.
    pub fn elided(line: &str) -> Quote {
        let line = line.lines().next().unwrap_or("").trim();
        let chars: Vec<char> = line.chars().collect();
        if chars.len() <= Self::MAX {
            return Quote(line.to_owned());
        }
        let keep = (Self::MAX - 1) / 2;
        let head: String = chars[..keep].iter().collect();
        let tail: String = chars[chars.len() - keep..].iter().collect();
        Quote(format!("{head}…{tail}"))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for Quote {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Diagnostic {
    pub severity: Severity,
    pub code: Code,
    pub message: String,
    pub location: Option<SourceLoc>,
    pub reference: Option<ScriptureRef>,
    pub help: Option<String>,
    pub quote: Option<Quote>,
    /// Raw backend text, collapsed by default in any UI (DIA-005).
    pub detail: Option<String>,
}

impl Diagnostic {
    pub fn new(severity: Severity, code: Code, message: impl Into<String>) -> Self {
        Diagnostic {
            severity,
            code,
            message: message.into(),
            location: None,
            reference: None,
            help: None,
            quote: None,
            detail: None,
        }
    }

    pub fn error(code: Code, message: impl Into<String>) -> Self {
        Self::new(Severity::Error, code, message)
    }

    pub fn warning(code: Code, message: impl Into<String>) -> Self {
        Self::new(Severity::Warning, code, message)
    }

    pub fn info(code: Code, message: impl Into<String>) -> Self {
        Self::new(Severity::Info, code, message)
    }

    pub fn at(mut self, loc: SourceLoc) -> Self {
        self.location = Some(loc);
        self
    }

    pub fn about(mut self, reference: ScriptureRef) -> Self {
        self.reference = Some(reference);
        self
    }

    pub fn help(mut self, help: impl Into<String>) -> Self {
        self.help = Some(help.into());
        self
    }

    pub fn quoting(mut self, line: &str) -> Self {
        self.quote = Some(Quote::elided(line));
        self
    }

    pub fn detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    pub fn stage(&self) -> Stage {
        self.code.stage()
    }
}

impl fmt::Display for Diagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}[{}]", self.severity, self.code)?;
        if let Some(loc) = &self.location {
            write!(f, " {loc}")?;
        }
        if let Some(r) = &self.reference {
            write!(f, " ({r})")?;
        }
        write!(f, ": {}", self.message)
    }
}

/// A collection with the one question the build orchestrator asks of it.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Diagnostics {
    items: Vec<Diagnostic>,
}

impl Diagnostics {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, d: Diagnostic) {
        self.items.push(d);
    }

    pub fn extend(&mut self, other: impl IntoIterator<Item = Diagnostic>) {
        self.items.extend(other);
    }

    pub fn iter(&self) -> impl Iterator<Item = &Diagnostic> {
        self.items.iter()
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// DIA-002: the build is blocked if any diagnostic blocks it, and the
    /// caller reports all of them before the backend is invoked.
    pub fn blocking(&self) -> impl Iterator<Item = &Diagnostic> {
        self.items.iter().filter(|d| d.severity.blocks())
    }

    pub fn has_blocking(&self) -> bool {
        self.items.iter().any(|d| d.severity.blocks())
    }

    pub fn by_stage(&self, stage: Stage) -> impl Iterator<Item = &Diagnostic> {
        self.items.iter().filter(move |d| d.stage() == stage)
    }
}

impl IntoIterator for Diagnostics {
    type Item = Diagnostic;
    type IntoIter = std::vec::IntoIter<Diagnostic>;
    fn into_iter(self) -> Self::IntoIter {
        self.items.into_iter()
    }
}

/// The codes BibleCompose emits. Grouped by stage; the string form is derived
/// from the stage, so the two cannot disagree.
pub mod code {
    crate::codes! {
        Discovery "PRJ" {
            DUPLICATE_BOOK_ID = "001",
            UNREADABLE_FILE = "002",
            NO_BOOKS_FOUND = "003",
        }
        Config "CFG" {
            INVALID_TOML = "001",
            UNKNOWN_KEY = "002",
            INVALID_UNIT = "003",
            UNKNOWN_SCHEMA_VERSION = "004",
        }
        Style "STY" {
            UNKNOWN_SELECTOR = "001",
            UNKNOWN_PROPERTY = "002",
            INHERITANCE_CYCLE = "003",
        }
        Asset "ASSET" {
            MISSING = "001",
            OUTSIDE_PROJECT = "002",
            UNSUPPORTED_FORMAT = "003",
        }
        Font "FONT" {
            UNRESOLVED = "001",
            MISSING_COVERAGE = "002",
            NO_HYPHENATION_PATTERNS = "004",
        }
        Backend "SILE" {
            NOT_FOUND = "001",
            VERSION_UNREADABLE = "002",
            NONZERO_EXIT = "003",
            NO_OUTPUT = "004",
            CANCELLED = "005",
            CLASS_VERSION_MISMATCH = "006",
            BUNDLE_UNPACK_FAILED = "007",
        }
        Output "OUT" {
            DESTINATION_LOCKED = "001",
            DESTINATION_UNWRITABLE = "002",
            PUBLISH_FAILED = "003",
        }
        Usfm "USFM" {
            // BibleCompose's own. Bare digits, deliberately: every code
            // `usfm-core` mints carries a severity letter, so the two
            // authorities minting `USFM-*` cannot collide. A test below
            // holds that line.
            UNSUPPORTED_MARKER = "003",

            // ---- mirrored from `usfm-core` ----
            //
            // ADR-001: parser diagnostics reach the panel unchanged rather
            // than re-coded, so a file reported one way in the editor is not
            // reported another way in the compositor.
            //
            // Declared here rather than derived, because this crate depends
            // on nothing (ARCHITECTURE §2) and must not grow a dependency on
            // the parser to describe its codes. `Deserialize` resolves
            // against `ALL`, so a build log containing one of these has to
            // round-trip, which it cannot do if the code is unlisted.
            //
            // Kept honest from the other side: `biblecompose-scripture`
            // maps every `usfm_core::DiagnosticCode` here through an
            // exhaustive match, so a code added upstream fails our build
            // rather than reaching a user as an unrecognised string.
            UNKNOWN_MARKER                     = "W001",
            DEPRECATED_MARKER                  = "W002",
            UNCLOSED_MARKER                    = "E003",
            STRAY_CLOSE_MARKER                 = "E004",
            MISNESTED_MARKER                   = "E005",
            MISSING_NESTING_PREFIX             = "E006",
            IMPLICIT_CLOSE                     = "E007",
            UNCLOSED_NOTE                      = "E008",
            UNCLOSED_AT_EOF                    = "E009",
            INVALID_CHAPTER_SEQUENCE           = "E010",
            INVALID_VERSE_SEQUENCE             = "E011",
            DUPLICATE_CHAPTER                  = "E012",
            DUPLICATE_ID                       = "E013",
            MISSING_ID_MARKER                  = "E014",
            INVALID_BOOK_CODE                  = "E015",
            NOTE_SUBMARKER_OUTSIDE_NOTE        = "E016",
            TEXT_BEFORE_ID                     = "E017",
            NON_ASCII_VERSE_DIGITS             = "E018",
            HEADER_AFTER_BODY                  = "W019",
            MILESTONE_MISMATCH                 = "E020",
            MIXED_NORMALIZATION                = "I021",
            JOINER_IN_MARKER_NAME              = "W022",
            JOINER_AT_MARKER_BOUNDARY          = "I023",
            INVALID_ATTRIBUTES                 = "E024",
            MISSING_CHAPTER_NUMBER             = "E025",
            MISSING_VERSE_NUMBER               = "E026",
            VERSE_OUTSIDE_PARAGRAPH            = "W027",
            MISSING_CHAPTER_MARKER             = "E028",
            CHAR_CROSSES_VERSE_BOUNDARY        = "W029",
            EMPTY_FIGURE                       = "W030",
            UNQUOTED_ATTRIBUTE_VALUE           = "W031",
            MISSING_REQUIRED_ATTRIBUTE         = "E032",
            DEFAULT_ATTRIBUTE_NOT_DEFINED      = "E033",
            BODY_PARAGRAPH_BEFORE_CHAPTER      = "W034",
            NON_EMPTY_BLANK_LINE               = "W035",
            LEADING_ZEROS                      = "W036",
            EMPTY_WORD_MARKER                  = "W037",
            MISSING_MILESTONE_SELF_CLOSE       = "E038",
            INVALID_TABLE_COLUMN_SEQUENCE      = "E039",
            MARKER_NEWER_THAN_DOCUMENT         = "I040",
            LEGACY_FIGURE_SYNTAX               = "W041",
            DUPLICATE_VERSE                    = "E042",
            VERSE_GAP                          = "I043",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// DIA-001. The macro makes a mismatch impossible to write; this asserts
    /// the invariant over every declared code, so a hand-rolled `__declare`
    /// bypassing the macro is caught too.
    #[test]
    fn every_code_carries_its_own_stage_prefix() {
        assert!(!code::ALL.is_empty());
        for c in code::ALL {
            let expected = format!("{}-", c.stage().prefix());
            assert!(
                c.as_str().starts_with(&expected),
                "code {} belongs to stage {} and must start with {expected}",
                c.as_str(),
                c.stage()
            );
        }
    }

    #[test]
    fn codes_are_unique() {
        let mut seen: Vec<&str> = code::ALL.iter().map(|c| c.as_str()).collect();
        seen.sort_unstable();
        let before = seen.len();
        seen.dedup();
        assert_eq!(before, seen.len(), "duplicate diagnostic code");
    }

    #[test]
    fn every_stage_has_a_distinct_prefix() {
        let mut prefixes: Vec<&str> = Stage::all().iter().map(|s| s.prefix()).collect();
        prefixes.sort_unstable();
        let before = prefixes.len();
        prefixes.dedup();
        assert_eq!(before, prefixes.len(), "two stages share a prefix");
    }

    #[test]
    fn blocking_is_only_errors() {
        let mut d = Diagnostics::new();
        d.push(Diagnostic::warning(code::UNKNOWN_KEY, "typo"));
        assert!(!d.has_blocking());
        d.push(Diagnostic::error(code::INVALID_TOML, "bad"));
        assert!(d.has_blocking());
        assert_eq!(d.blocking().count(), 1);
    }

    #[test]
    fn quote_elides_long_lines_and_keeps_short_ones() {
        let short = Quote::elided("  In the beginning  ");
        assert_eq!(short.as_str(), "In the beginning");

        let long = "x".repeat(500);
        let q = Quote::elided(&long);
        assert!(q.as_str().chars().count() <= Quote::MAX);
        assert!(q.as_str().contains('…'));
    }

    #[test]
    fn quote_takes_only_the_first_line() {
        let q = Quote::elided("first line\nsecond line\nthird");
        assert_eq!(q.as_str(), "first line");
    }

    #[test]
    fn display_is_readable() {
        let d = Diagnostic::error(code::DUPLICATE_BOOK_ID, "two files declare \\id MAT")
            .at(SourceLoc::at("books/MAT.usfm", 1, 1));
        assert_eq!(
            d.to_string(),
            "error[PRJ-001] books/MAT.usfm:1:1: two files declare \\id MAT"
        );
    }
}
